feat(build): add scripts for all yarn commands

diff --git a/scripts/bump-version b/scripts/bump-version
--- a/scripts/bump-version
+++ b/scripts/bump-version
@@ -7,29 +7,17 @@
 # 
 # Remember to run this script from the root of the project!
 
-# ANSI colour codes so we can highlight text in the terminal
-colour_black="\033[0;30m"
-colour_darkgray="\033[1;30m"
-colour_red="\033[0;31m"
-colour_lightred="\033[1;31m"
-colour_green="\033[0;32m"
-colour_lightgreen="\033[1;32m"
-colour_orange="\033[0;33m"
-colour_yellow="\033[1;33m"
-colour_blue="\033[0;34m"
-colour_lightblue="\033[1;34m"
-colour_purple="\033[0;35m"
-colour_lightpurple="\033[1;35m"
-colour_cyan="\033[0;36m"
-colour_lightcyan="\033[1;36m"
-colour_lightgray="0;\033[37 m"
-colour_white="\033[1;37m"
+# Fail fast
+set -e
 
-# Escape codes for making text bold, italic, etc.
+# ANSI colour codes so we can highlight text in the terminal
+colour_red="\033[0;31m"
+colour_green="\033[0;32m"
+colour_blue="\033[0;34m"
+colour_cyan="\033[0;36m"
+
+# Escape codes for making text bold and returning it back to normal
 bold="\e[1m"
-italic="\e[3m"
-underline="\e[4"
-strikethrough="\e[9"
 normal="\e[0m"
 
 # Display a help message
@@ -48,7 +36,7 @@ function bump {
 	local npm_command=$(which npm)
 	if [ -z npm_command ]; then
 		# If not, throw an error
-		echo -e "${red}NodeJS and NPM must be installed!${red}"
+		echo -e "${colour_red}NodeJS and NPM must be installed!${colour_red}"
 		exit 1
 	fi
 
@@ -78,9 +66,12 @@ function add_release_notes {
 	local git_command=$(which git)
 	if [ -z git_command ]; then
 		# If not, throw an error
-		echo -e "${red}Git must be installed!${red}"
+		echo -e "${colour_red}Git must be installed!${colour_red}"
 		exit 1
 	fi
+
+	# Do a git fetch to get new tags (if any)
+	git fetch origin --quiet
 
 	# Get the new version
 	local new_release_tag=`cat version`
@@ -115,9 +106,9 @@ function push_to_git {
 	# NOTE: Do not tag the commit, as the CI will then not create a release
 	# Pre-releases will contain a dash in their version
 	if [[ $new_release_tag =~ "-" ]]; then
-		git commit --signoff -m "chore(release): prerelease $new_release_tag"
+		git commit -m "chore(release): prerelease $new_release_tag"
 	else
-		git commit --signoff -m "chore(release): release $new_release_tag"
+		git commit -m "chore(release): release $new_release_tag"
 	fi
 	
 	# Push the changes
